import assert from "node:assert/strict";
import {adjudicationBoundary870 as a} from "../tools/adjudicationBoundary870.mjs";
const b={meaning:{challengeRaised:true,routeUsable:true,examined:true,reasonsGiven:true,disposition:"accepted"},
 merits:{firstOrder:"support",provenance:"independent_declared",higherOrderChallenge:"examined"},victimStanding:"considered_declared"};
const f=p=>a({...b,...p,meaning:{...b.meaning,...(p.meaning||{})},merits:{...b.merits,...(p.merits||{})}});
assert.equal(f({}).meaningStatus,"ATTRIBUTION_REVISED_DECLARED");
assert.equal(f({}).factStatus,"ACT_SUPPORT_DECLARED_NOT_AUTHENTICATED");
assert.equal(f({meaning:{disposition:"rejected"}}).meaningStatus,"ATTRIBUTION_DISAGREEMENT_REASONED_DECLARED");
assert.equal(f({meaning:{disposition:"rejected"}}).factStatus,f({}).factStatus);
assert.equal(f({merits:{firstOrder:"counterevidence"}}).meaningStatus,f({}).meaningStatus);
assert.equal(f({merits:{firstOrder:"counterevidence"}}).factStatus,"ACT_COUNTEREVIDENCE_DECLARED_NOT_AUTHENTICATED");
assert.equal(f({meaning:{routeUsable:false}}).meaningStatus,"OBJECTION_ROUTE_BLOCKED");
assert.equal(f({meaning:{examined:false}}).meaningStatus,"OBJECTION_NOT_EXAMINED");
assert.equal(f({meaning:{reasonsGiven:false}}).meaningStatus,"OBJECTION_NO_REASONS");
assert.equal(f({meaning:{disposition:"unresolved"}}).meaningStatus,"ATTRIBUTION_UNRESOLVED");
assert.equal(f({merits:{provenance:"shared_root"}}).factStatus,"DEPENDENCE_DEFEATER");
assert.equal(f({merits:{provenance:"unexamined"}}).factStatus,"PROVENANCE_UNEXAMINED");
assert.equal(f({merits:{higherOrderChallenge:"raised_unexamined"}}).factStatus,"CREDIBILITY_DEFEATER_UNEXAMINED");
assert.equal(f({merits:{firstOrder:"insufficient"}}).factStatus,"ACT_EVIDENCE_INSUFFICIENT");
assert.equal(f({victimStanding:"not_declared"}).meaningStatus,f({}).meaningStatus);
assert.equal(f({victimStanding:"not_declared"}).victimStanding,"not_declared");
assert.equal(f({}).meaningCorrectionChangesMeritsByDefinition,false);
assert.equal(f({}).meaningRejectionCertifiesMisconduct,false);
assert.equal(f({}).authenticatedProvenance,false);
assert.equal(f({}).actualJustificationCertified,false);
assert.equal(f({}).realWorldReliefCertified,false);
assert.throws(()=>f({meaning:{challengeRaised:false}}));
assert.throws(()=>f({merits:{higherOrderChallenge:"verified_truth"}}));
assert.throws(()=>f({victimStanding:"ignored"}));
console.log("NOMOS 0.870 boundary court: PASS 24 assertions");
